name: BorderLevel
version: ${project.version}
main: org.funty.borderlevel.Main
api-version: 1.17
authors: [Funty]
website: Funty.org

commands:
  borderlevel:
    aliases:
      - bl
      - borderl
      - blevel
      - blvl
      - borderlvl